
# Imports 

```{r}
# path to results and to save everything
dir_to_save_fig <-  "../../output_figures/NMF/"
dir.create(file.path(".", dir_to_save_fig), showWarnings = F, recursive = T)


unloadNamespace("linseed2")
devtools::load_all(path='../../../linseed2/')
source('nmf_methods.R')
source("../figure_utils.R") # for same colors
```

# Read saved NMF results
```{r}
current_K <- 4
current_M <- 16384
current_N <- 100
```

```{r}
file_name <- paste0(dir_to_save_fig, 'pictures_', current_K ,'K_', current_N, 'N_', current_M, 'M_random-H_10runs_10init.rds')
result_random <- readRDS(file=file_name)

```

# Draw result pictures obtained by each method

```{r}
t <- plot_pictures_for_result(result_random$fit_objects, model_index = 10, dir_to_save_fig)
```

```{r fig.height = 5, fig.width = 20}
distances_to_check_random <- plot_metrics_box(res_methods = result_random$fit_objects, 
                                         data_used=result_random$data_used, 
                                         title=paste("Random: K =", as.character(current_K), "M =", as.character(current_M),"N =",as.character(current_N)),
                                         dir_to_save_fig)
distances_to_check_random$plot
```

```{r fig.height = 5, fig.width =20}
distances_to_check_random$per_comp_plot_h
```


```{r}
plot_w_h_v(W=result_random$data_used[[1]]$true_W, 
           H = result_random$data_used[[1]]$true_H, 
           V=result_random$data_used[[1]]$V, )
```
# Simplex generated proportions result



```{r}
file_name <- paste0(dir_to_save_fig, 'pictures_', current_K ,'K_', current_N, 'N_', current_M, 'M_simplex-H_10runs_10init.rds')
result_simplex <- readRDS(file=file_name)
```

## Investigate single object
```{r}
lo2 <- result_simplex$fit_objects$`Linseedv2 NMF`[[1]]$obj
```

## Plot nice visualization with plotly
```{r}
library(plotly)
dims <-  lo2$st$n_cell_types
X <- lo2$st$solution_proj$X
Omega <- t(lo2$st$solution_proj$Omega)

X <- X[,1:dims]
Omega <- Omega[1:dims,]

## plot X
toPlotX <- as.data.frame(lo2$st$proj$X)[,1:dims]
colnames(toPlotX) <- paste0("R", c(1:dims))
colnames(X) <- paste0("R", c(1:dims))



Omega <- Omega[1:dims,]
## plot X
toPlotOmega <- as.data.frame(lo2$st$proj$Omega)[,1:dims]
colnames(toPlotOmega) <- paste0("S", c(1:dims))
rownames(Omega) <-  paste0("S", c(1:dims))

```


```{r}
n <- 2
l <- rep(list(1:nrow(X)), n)
permutations <- expand.grid(l)
indices <-  c(t(as.matrix(permutations[permutations[,"Var1"] < permutations[, 'Var2'],] )))
X_points <- X[indices,]
Omega_points <- X[indices,]

t <- list(
  family = "Helvetica",
  size = 30)

fig_X <- plot_ly(toPlotX,  width = 500, height = 500) %>%  config(toImageButtonOptions = list(format = "svg",      
                                                                                                      width = 600,
                                                                                                      height = 600))

fig_X <-fig_X %>% add_trace( x = ~R2, y = ~R3, z = ~R4, size=1, marker = list(symbol = 'circle', color = "gray", opacity = 0.8, line = list(
        color = 'black',
        width = 1
      ))    )

fig_X <- fig_X %>% add_trace(x = X_points[,'R2'], y = X_points[,'R3'], z = X_points[,'R4'],
            line = list(color = 'rgb(44, 160, 44)', width = 5))
fig_X <- fig_X %>% layout(showlegend = FALSE, 
                          
                          scene = list(xaxis = list(title = 'R2',  titlefont = t),

                          yaxis = list(title = 'R3', titlefont = t),

                     zaxis = list(title = 'R4', titlefont = t))
                  
                          ) %>% config(toImageButtonOptions = list(format = "svg", width = 600,
                                                              height = 600))


fig_X
```


```{r}
n <- 2
l <- rep(list(1:nrow(X)), n)
permutations <- expand.grid(l)
indices <-  c(t(as.matrix(permutations[permutations[,"Var1"] < permutations[, 'Var2'],] )))
Omega_points <- Omega[,indices]


fig_Omega <- plot_ly(toPlotOmega,  width = 500, height = 500) %>%  config(toImageButtonOptions = list(format = "svg",      
                                                                                                      width = 600,
                                                                                                      height = 600))

fig_Omega <-fig_Omega %>% add_trace( x = ~S2, y = ~S3, z = ~S4, size=3, marker = list(symbol = 'circle', size=5,  color = "gray", line = list(
        color = 'black',
        width = 3
      ))    )

fig_Omega <- fig_Omega %>% add_trace(x = Omega_points['S2',], y = Omega_points['S3',], z = Omega_points['S4',],
            line = list(color = 'rgb(44, 160, 44)', width = 5))
fig_Omega <- fig_Omega %>% layout(showlegend = FALSE,
                                  scene = list(xaxis = list(title = 'S2',  titlefont = t),
                                  yaxis = list(title = 'S3', titlefont = t),
                                  zaxis = list(title = 'S4', titlefont = t))
                  ) %>% config(toImageButtonOptions = list(format = "svg", width = 600,
                                                              height = 600))

fig_Omega
```
## Plot example of mixed picture

```{r}
picture_title <- "mixed_picture1"
filename <- paste0(dir_to_save_fig, picture_title, ".jpeg")
jpeg(filename, width = 400, height = 400)

V_matrix <- result_simplex$data_used[[1]]$V
size <- as.integer(sqrt(dim(V_matrix)[[1]]))
par(mar=c(0, 0, 0,0), oma=c(0, 0, 0,0)) # all sides have 3 lines of space
  image(tf(matrix(V_matrix[, 17], nrow = size, ncol = size, byrow = TRUE)),
       col=grey(seq(0, 1, length = 256)), axes = FALSE)
dev.off()
```

## Boxplots


```{r}
distances_to_check_simplex <- plot_metrics_box(res_methods = result_simplex$fit_objects, 
                                         data_used=result_simplex$data_used, 
                                         title=paste("Simplex: K =", as.character(current_K), "M =", as.character(current_M),"N =",as.character(current_N)),
                                         dir_to_save_fig)
```




