---
title: "Animation of Sinkhorn Transformation"
output:
  html_document:
    df_print: paged
    self_contained: yes
---

```{r}
source("../R/setup.R")
library(ggplot2)
library(gganimate)
library(dplyr)
```


```{r, fig.width=4, fig.height=20}
set.seed(4)
sim <- create_simulation(1000, 100, 3, with_marker_genes = T) %>% add_basis_samples()

scaling <- sinkhorn_scale(sim$data, 10)
proj <- svd_project(scaling, 1:100)
```



# Sinkhorn research
```{r, fig.width=4, fig.height=4}
# 2:3 dim projections on different Sinkhorn iterations
plotlist <- list()
for (i in 1:10) {
  this_scaling <- sinkhorn_scale(sim$data, i)
  this_proj <- svd_project(this_scaling, 1:100)
  dims <- 2:3
  plotlist[[(i - 1) * 2 + 1]] <- plot_projection_points(this_proj, dims, spaces = "X")
  plotlist[[i * 2]] <- plot_projection_points(this_proj, dims, spaces = "Omega")
}

plotlist
```

```{r}
data <- sim$data - rowMeans(sim$data)
svd_ <- svd(data)

S <- t(svd_$u[, 1:2])
R <- t(svd_$v[, 1:2])

plot(data %*% t(R))
plot(t(S %*% data))
```

```{r}
data <- sim$data
data <- data / rowSums(data)
svd_ <- svd(data)

S <- t(svd_$u[, 2:3])
R <- t(svd_$v[, 2:3])

plot(data %*% t(R))
plot(t(S %*% data))
```

```{r}
data <- data / colSums(data)
svd_ <- svd(data)

S <- t(svd_$u[, 2:3])
R <- t(svd_$v[, 2:3])

plot(data %*% t(R))
plot(t(S %*% data))
```

```{r}
prev_md <- min(colSums(sim$data))
prev_mxd <- max(colSums(sim$data))
for (i in 1:12) {
  scaling <- sinkhorn_scale(sim$data, i)
  v_column_sums <- colSums(scaling$V_row)
  cur_md <- min(v_column_sums)
  cur_mxd <- max(v_column_sums)
  if (i != 1) {
    plot(v_column_sums, ylim = c(prev_md, prev_mxd), pch = ".", cex = i)
    title("After Scaling Step")
    abline(h = cur_md, col = "red")
    abline(h = nrow(sim$data) / ncol(sim$data), col = "blue")
    abline(h = cur_mxd, col = "red")
  }
  plot(v_column_sums, ylim = c(cur_md, cur_mxd), pch = ".", cex = i)
  title("Current Data Zoom")
  abline(h = cur_md, col = "red")
  abline(h = nrow(sim$data) / ncol(sim$data), col = "blue")
  abline(h = cur_mxd, col = "red")
  prev_md <- cur_md
  prev_mxd <- cur_mxd
  # plot(rowSums(scaling$V_column), ylim = c(0.745, 0.785), pch = ".")
}
plot(v_column_sums, ylim = c(cur_md, cur_mxd), pch = ".", cex = i)
title("Final Result")
plot(v_column_sums, ylim = c(cur_md, cur_mxd), pch = ".", cex = 1)
title("Final Result with Small Points")
```


# Animation
```{r}
dso <- DualSimplexSolver$new()
dso$set_data(sim$data)
dso$project(3)
dso$init_solution("random")
dso$optim_solution(6000)
dso$plot_projected(use_dims = 2:3)
```


```{r}
is_X <- F
if (is_X) {
  limits <- c(-0.15, 0.15)
  zero_y <- -0.009
  zero_x <- -0.009
  ax_len <- 0.125
  pt_size <- 1
  pt_alpha <- 0.4
} else {
  limits <- c(-0.05, 0.05)
  zero_y <- -0.005
  zero_x <- -0.005
  ax_len <- 0.04
  pt_size <- 1.5
  pt_alpha <- 0.4
}
```

```{r}
plotly::plot_ly(
  data.frame(c(1)),
  x = 0,
  y = 0,
  z = 0,
  size = 0,
  type = "scatter3d",
  mode = "markers",
  marker = list(color = "white", line = list(width = 0))
) %>%
  plotly::layout(
    scene = list(
      camera = list(
        eye = list(x = 2.3, y = 1.4, z = 0.7)
      ),
      xaxis = list(tickfont = list(size = 15), title = "", gridwidth = 3, ticktextposition = 4, range = limits),
      yaxis = list(tickfont = list(size = 15), title = "", gridwidth = 3, ticktextposition = 4, range = c(-0.06, 0.06)),
      zaxis = list(tickfont = list(size = 15), title = "", gridwidth = 3, ticktextposition = 4, range = c(-0.06, 0.06))
    )
  ) %>%
  plotly::config(
    toImageButtonOptions = list(
      format = "png",
      filename = if(is_X) "grid_image_X" else "grid_image_Omega",
      width = 1200,
      height = 1220,
      scale = 6
    )
  )
```


```{r fig.width=3, fig.height=3}
test <- F

points_col <- RColorBrewer::brewer.pal(9, if (is_X) "Blues" else "Oranges")

animated_data <- data.frame(V1 = numeric(), V2 = numeric(), step = integer())
if (is_X) {
  xs <- c(1, 0.55, 0.85, 0.52, 0.5)
} else {
  xs <- c(1, 0.85, 0.5, 0.7, 0.5)
}

pt_stroke <- pt_size / 7
ax_width <- 0.07
#arr_ow <- arrow(length = unit(0.3, "cm"))
seg <- function(length, angle) {
  angle <- angle * (pi / 180)
  xend <- zero_x + length * cos(angle)
  yend <- zero_y + length * sin(angle)
  return(aes(x = zero_x, y = zero_y, xend = xend, yend = yend))
}

for (i in seq_along(xs)) {
  x <- xs[i]
  if (is_X) {
    to_plot <- proj$X[, 2:3]
  } else {
    to_plot <- proj$Omega[, 2:3]
  }
  transform <- t(matrix(c(1, 0, 0, 0.6 + (0.7 - 0.6) * i / length(xs)), nrow = 2))
  noise <- matrix(rnorm(n = nrow(to_plot) * 2, mean = 1, sd = (x - 0.5) * 3), ncol = 2)
  to_plot <- to_plot * noise
  to_plot <- to_plot %*% transform
  to_plot[, 1] <- pmax(limits[1], pmin(to_plot[, 1], limits[2]))
  to_plot[, 2] <- pmax(limits[1], pmin(to_plot[, 2], limits[2]))
  to_plot <- data.frame(to_plot, step = rep(i, nrow(to_plot)), point_id = rownames(to_plot))
  animated_data <- rbind(animated_data, to_plot)
}

colnames(animated_data)[1:2] <- c("V1", "V2")

animated_data$point_id <- as.factor(animated_data$point_id)

if (test) {
  animated_data <- animated_data[animated_data$step == 4, ]
}
```

```{r fig.width=3, fig.height=3}
img <- png::readPNG(if (is_X) "~/Downloads/grid_image_X.png" else "~/Downloads/grid_image_Omega.png")

g <- grid::rasterGrob(img, interpolate = T)

p <- ggplot(animated_data, aes(x = V1, y = V2, group = point_id)) +
  annotation_custom(g, xmin=limits[1] * 1.6, xmax=limits[2] * 1.6, ymin=-Inf, ymax=Inf) +
  geom_point(
    size = pt_size,
    col = points_col[7],
    fill = alpha(points_col[4], pt_alpha),
    shape = 21,
    stroke = pt_stroke
  ) +
  theme_minimal() +
  theme(axis.title = element_blank(), panel.grid = element_blank(), axis.text = element_blank(), legend.position = "none") +
  xlim(limits * 1.6) + ylim(limits * 1.6)


if (test) {
  p
} else {
  p <- p + transition_states(step, state_length = 2, transition_length = 1, wrap = F) +
    ease_aes('exponential-in-out') +
    labs(title = if (is_X) "X space, Sinkhorn step: {closest_state}" else "Omega space, Sinkhorn step: {closest_state}")
  animate(
    p,
    renderer = ffmpeg_renderer(format = "mp4", options = list(pix_fmt = "yuv420p", vcodec = "libx264")),
    height = 1220,
    width = 1200,
    duration = 8,
    start_pause = 1,
    end_pause = 1,
    fps = 25,
    end_pause = 0,
    res = 300
  )
  if (is_X) {
    anim_save("../out/sinkhorn_animation_x.mp4")
  } else {
    anim_save("../out/sinkhorn_animation_omega.mp4")
  }
}
```



```{r}
mx_step <- max(animated_data$step)
animated_data_2 <- animated_data[animated_data$step == mx_step, ]
if (is_X) {
  to_plot <- proj$X[, 2:3]
} else {
  to_plot <- proj$Omega[, 2:3]
}
transform <- t(matrix(c(1, 0, 0, 1), nrow = 2))
to_plot <- to_plot %*% transform
to_plot <- data.frame(to_plot, step = rep(mx_step + 1, nrow(to_plot)), point_id = rownames(to_plot))
colnames(to_plot)[1:2] <- c("V1", "V2")
animated_data_2 <- rbind(animated_data_2, to_plot)

animated_data_2$point_id <- as.factor(animated_data_2$point_id)
```


```{r}
p <- ggplot(animated_data_2, aes(x = V1, y = V2, group = point_id)) +
    geom_point(
    size = pt_size,
    col = points_col[7],
    fill = alpha(points_col[4], pt_alpha),
    shape = 21,
    stroke = pt_stroke
  ) +
  theme_minimal() +
  theme(axis.title = element_blank(), panel.grid = element_blank(), axis.text = element_blank(), legend.position = "none") +
  xlim(limits) + ylim(limits) +
  transition_states(step, state_length = 1, transition_length = 3, wrap = F) +
  ease_aes('exponential-in-out') +
  labs(title = if (is_X) "X space projection" else "Omega space projection")

animate(
  p,
  renderer = ffmpeg_renderer(format = "mp4", options = list(pix_fmt = "yuv420p", vcodec = "libx264")),
  height = 1220,
  width = 1200,
  duration = 1,
  start_pause = 1,
  end_pause = 1,
  fps = 25,
  end_pause = 0,
  res = 300
)

if (is_X) {
  anim_save("../out/proj_animation_x.mp4")
} else {
  anim_save("../out/proj_animation_omega.mp4")
}
```


```{r}
mx_step <- max(animated_data_2$step)
animated_data_3 <- animated_data_2[animated_data_2$step == mx_step, ]
if (is_X) {
  to_plot <- proj$X[, 2:3]
} else {
  to_plot <- proj$Omega[, 2:3]
}
transform <- t(matrix(c(2, 0, 0, 2), nrow = 2))
to_plot <- to_plot %*% transform
to_plot <- data.frame(to_plot, step = rep(mx_step + 1, nrow(to_plot)), point_id = rownames(to_plot))
colnames(to_plot)[1:2] <- c("V1", "V2")
animated_data_3 <- rbind(animated_data_3, to_plot)

animated_data_3$point_id <- as.factor(animated_data_3$point_id)
limits <- limits * 1.1
```


```{r}
p <- ggplot(animated_data_3, aes(x = V1, y = V2, group = point_id)) +
    geom_point(
      size = pt_size * 2,
      col = points_col[7],
      fill = alpha(points_col[4], pt_alpha),
      shape = 21,
      stroke = pt_stroke
    ) +
    theme_minimal() +
    theme(axis.title = element_blank(), panel.grid = element_blank(), axis.text = element_blank(), legend.position = "none") +
    xlim(limits) + ylim(limits) +
    transition_states(step, state_length = 3, transition_length = 2, wrap = F) +
    ease_aes('exponential-in-out') +
    labs(title = if (is_X) "X space projection" else "Omega space projection")

animate(
  p,
  renderer = ffmpeg_renderer(format = "mp4", options = list(pix_fmt = "yuv420p", vcodec = "libx264")),
  height = 1220,
  width = 1200,
  fps = 25,
  res = 300,
  duration = 4
)

if (is_X) {
  anim_save("../out/zoom_animation_x.mp4")
} else {
  anim_save("../out/zoom_animation_omega.mp4")
}
```


```{r}
mx_step <- max(animated_data_3$step)
animated_data_4 <- animated_data_3[animated_data_3$step == mx_step, ]
```


```{r}
p <- ggplot(animated_data_4, aes(x = V1, y = V2, group = point_id)) +
    geom_point(
      size = pt_size * 2,
      col = points_col[7],
      fill = alpha(points_col[4], pt_alpha),
      shape = 21,
      stroke = pt_stroke
    ) +
    theme_minimal() +
    theme(axis.title = element_blank(), axis.text = element_blank(), legend.position = "none") +
    xlim(limits) + ylim(limits) +
    transition_states(step, state_length = 1, transition_length = 1, wrap = F) +
    ease_aes('exponential-in-out') +
    labs(title = if (is_X) "X space projection" else "Omega space projection")

animate(
  p,
  renderer = ffmpeg_renderer(format = "mp4", options = list(pix_fmt = "yuv420p", vcodec = "libx264")),
  height = 1220,
  width = 1200,
  duration = 5,
  fps = 25,
  res = 300
)

if (is_X) {
  anim_save("../out/axis_animation_x.mp4")
} else {
  anim_save("../out/axis_animation_omega.mp4")
}
```


```{r}
history <- get_solution_history(dso$st$solution_proj, 2)
solution <- dso$st$solution_proj

if (is_X) {
  history <- history$X
  solution <- solution$X
} else {
  history <- history$Omega
  solution <- solution$Omega
}

solution <- as.data.frame(solution)

solution$point <- as.factor(1:3)

transform <- t(matrix(c(2, 0, 0, 2), nrow = 2))
history[, 2:3] <- as.data.frame(as.matrix(history[, 2:3]) %*% transform)
solution[, 2:3] <- as.data.frame(as.matrix(solution[, 2:3]) %*% transform)
```


```{r}
p <- ggplot(animated_data_4, aes(x = V1, y = V2, group = point_id)) +
    geom_point(
      size = pt_size * 2,
      col = points_col[7],
      fill = alpha(points_col[4], pt_alpha),
      shape = 21,
      stroke = pt_stroke
    ) +
    geom_path(
      data = history,
      aes(dim_2, dim_3, col = point, group = point),
      size = 0.7
    ) +
    geom_point(
      data = solution,
      aes(dim_2, dim_3, col = point, group = point),
      size = 2.5
    ) +
    theme_minimal() +
    theme(axis.title = element_blank(), axis.text = element_blank(), legend.position = "none") +
    xlim(limits) + ylim(limits) +
    transition_states(step, state_length = 1, transition_length = 3, wrap = F) +
    ease_aes('exponential-in-out') +
    labs(title = if (is_X) "X space projection" else "Omega space projection")

animate(
  p,
  renderer = ffmpeg_renderer(format = "mp4", options = list(pix_fmt = "yuv420p", vcodec = "libx264")),
  height = 1220,
  width = 1200,
  duration = 5,
  fps = 25,
  res = 300
)

if (is_X) {
  anim_save("../out/optim_animation_x.mp4")
} else {
  anim_save("../out/optim_animation_omega.mp4")
}
```
