---
title: "Figure 6: Application of DualSimplex to single cell data"
output:
  html_document:
    df_print: paged
    self_contained: yes
---

```{r}
source("../R/setup.R")
library(ggplot2)
library(Seurat)
library(systemfonts)
options("dualsimplex-rasterize" = T)
```

```{r}
so <- readRDS("../data/large/GSE103322.rds")
```

```{r, fig.width=7, fig.height=5}
ct_mapping = list(
  "0" = "Cancer",
  "Fibroblast" = "Fibroblast",
  "B cell" = "B cell",
  "myocyte" = "Myocyte",
  "-Fibroblast" = "CAF",
  "Macrophage" = "Macrophage",
  "Endothelial" = "Endothelial",
  "T cell" = "T cell",
  "Dendritic" = "Dentritic",
  "Mast" = "Mast"
)
so@meta.data[, "ct"] <- unname(sapply(so@meta.data$ct, function(x) ct_mapping[[x]]))
Idents(so) <- "ct"
DimPlot(so)
```

```{r}
data <- so@assays$RNA@counts
data <- as.matrix(data)
data <- 2^data
dim(data)
```


```{r}
stat_list <- apply(data, 1, LogVMR)
hist(stat_list, breaks = 100)
```

```{r}
so <- Seurat::FindVariableFeatures(so, nfeatures = 3000)
flt_genes <- so@assays$RNA@var.features
flt_genes <- flt_genes[flt_genes %in% rownames(data)]
```


```{r, fig.width=13, fig.height=5}
top10 <- head(VariableFeatures(so), 10)
plot1 <- VariableFeaturePlot(so)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
```

```{r}
dso <- DualSimplexSolver$new()
dso$set_data(data[flt_genes, ])
```

```{r}
dso$plot_svd(1:1000)
```

```{r}
dim(dso$get_data())
```


```{r}
dso$plot_mad()
dso$plot_svd()
```

```{r}
dso$plot_svd(1:100)
```

```{r}
dso$project(16)
```

```{r}
dso$run_umap(neighbors_X = 30, neighbors_Omega = 15)
```

```{r, fig.width=12, fig.height=6}
dso$plot_projection_diagnostics()
```

```{r}
dso$distance_filter(zero_d_lt = 0.2, genes = F)
```

```{r, fig.width=12, fig.height=6}
dso$plot_svd(1:100)
dso$project(20)
dso$run_umap(neighbors_X = 20, neighbors_Omega = 15)
dso$plot_projection_diagnostics()
```

```{r}
dso$distance_filter(zero_d_lt = 0.16, genes = F)
```

```{r, fig.width=12, fig.height=6}
dso$plot_svd()
dso$project(20)
dso$run_umap(neighbors_X = 20, neighbors_Omega = 15)
dso$plot_projection_diagnostics()
```

```{r}
dso$distance_filter(plane_d_lt = 0.15, genes = T)
```

```{r, fig.width=12, fig.height=6}
dso$plot_svd()
dso$project(20)
dso$run_umap(neighbors_X = 20, neighbors_Omega = 15)
dso$plot_projection_diagnostics()
```

```{r}
dso$distance_filter(zero_d_lt = 0.05, genes = T)
```

```{r, fig.width=12, fig.height=6}
dso$plot_svd()
dso$project(20)
dso$run_umap(neighbors_X = 20, neighbors_Omega = 15)
dso$plot_projection_diagnostics()
```

```{r, fig.width=7, fig.height=5}
DimPlot(so, cells.highlight = list(filtered = colnames(so)[!colnames(so) %in% colnames(dso$get_data())]))
```

```{r}
so_flt <- so[, colnames(so) %in% colnames(dso$get_data())]
```

```{r, fig.width=7, fig.height=5}
DimPlot(so_flt)
```


```{r}
dso$save_state("../out/single_cell_hnsc_save_3kg/")
dso <- DualSimplexSolver$from_state("../out/single_cell_hnsc_save_3kg/")
```


## Final projection
```{r}
dso$plot_svd(1:100)
```

```{r}
all_dims <- list(NULL, 2:3, 4:5, 6:7, 8:9, 10:11, 12:13, 14:15, 16:17, 18:19, 20:21)
dso$project(16)
```

```{r fig.width=13, fig.height=6}
set.seed(24)
dso$run_umap(neighbors_X = 20, neighbors_Omega = 10)
dso$plot_projected(use_dims = NULL, with_solution = F, with_history = F)
dso$plot_projected(
  color_genes = "zero_distance",
  color_samples = as.factor(so_flt[, colnames(dso$get_data())]$ct),
  use_dims = NULL,
  pt_size = 0.5,
  with_legend = T,
  with_solution = F,
  with_history = F
)
```


```{r, fig.width=12, fig.height=6}
so_flt$zero_distance <- pData(dso$get_data())[colnames(so_flt), "zero_distance"]
so_flt$plane_distance <- pData(dso$get_data())[colnames(so_flt), "plane_distance"]
pal <- rev(RColorBrewer::brewer.pal(11, "Spectral"))
cowplot::plot_grid(
  FeaturePlot(so_flt, feature = "zero_distance", cols = pal) + NoLegend(),
  FeaturePlot(so_flt, feature = "plane_distance", cols = pal) + NoLegend()
)
```


```{r}
dso$save_state("../out/single_cell_hnsc_save_3kg_16ct/")
dso <- DualSimplexSolver$from_state("../out/single_cell_hnsc_save_3kg_16ct/")
```


## Solve deconvolution
```{r, fig.width=12, fig.height=6}
set.seed(21)
dso$init_solution("select_x")
dso$plot_projected()
```


## Optimize solution
```{r fig.width = 14, fig.height = 6}
dso$optim_solution(
  650,
  optim_config(
    coef_hinge_H = 1,
    coef_hinge_W = 1,
    coef_der_X = 0.001,
    coef_der_Omega = 0.1
  )
)
dso$plot_projected(use_dims = NULL, with_legend = T, from_iter = 1, to_iter = 650)
```


```{r}
lr <- 0.001
dso$optim_solution(
  1000,
  optim_config(
    coef_hinge_H = .01,
    coef_hinge_W = .01,
    coef_der_X = lr,
    coef_der_Omega = lr
  )
)
dso$plot_error_history()
```


```{r fig.width = 13, fig.height = 6}
dso$plot_projected(use_dims = NULL, with_legend = T)
```


## Check corner points
```{r, fig.width=12, fig.height=6}
knns <- FNN::get.knnx(dso$st$proj$X, dso$st$solution_proj$X, k = 40)
corner_genes <- as.list(as.data.frame(
  apply(knns$nn.index, 1, function(x) rownames(dso$get_data())[x])
))
knns_cells <- FNN::get.knnx(dso$st$proj$Omega, dso$st$solution_proj$Omega, k = 70)
corner_cells <- as.list(as.data.frame(
  apply(knns_cells$nn.index, 1, function(x) colnames(dso$get_data())[x])
))
kmeans_cells_clustering <- stats::kmeans(dso$st$proj$Omega, centers = dso$st$solution_proj$Omega)
```

```{r, fig.width=12, fig.height=6}
dso$plot_projected(
  color_genes = "zero_distance",
  color_samples = as.factor(so_flt[, colnames(dso$get_data())]$ct),
  use_dims = NULL,
  pt_size = 0.5,
  with_legend = T,
  with_solution = F,
  with_history = F
)

dso$plot_projected(
  color_genes = which_marker(rownames(dso$get_data()), corner_genes),
  color_samples = which_marker(colnames(dso$get_data()), corner_cells),
  with_solution = T,
  with_history = T,
  color_history = F,
  with_legend = F,
  use_dims = NULL
)

dso$plot_projected(
  color_genes = which_marker(rownames(dso$get_data()), corner_genes),
  color_samples = as.factor(kmeans_cells_clustering$cluster),
  with_solution = T,
  with_history = F,
  with_legend = F,
  use_dims = NULL
)
```

```{r fig.width=5, fig.height=5}
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

so_flt$marker_cell <- which_marker(colnames(so), corner_cells)
so_flt$kmeans_cluster <- kmeans_cells_clustering$cluster[colnames(so_flt)]
DimPlot(so_flt, group.by = "marker_cell", na.value = "grey92", cols = gg_color_hue(dso$get_n_cell_types())) + NoLegend() + ggtitle("") + NoAxes()
DimPlot(so_flt, group.by = "kmeans_cluster", label=T) + NoLegend() + ggtitle("") + NoAxes()
```

```{r}
ae <- AverageExpression(so_flt, group.py = "kmeans_cluster")
write.csv(ae$RNA, "../out/pseudo_bulk_16ct.csv", quote = F)
```

```{r}
cat_markers(dso$get_marker_genes())
dso$save_solution("../out/single_cell_hnsc_save_3kg_16ct/")
```

```{r fig.width=20, fig.height=25}
so <- add_list_markers(so, corner_genes)
plot_marker_enrichment(so, names(corner_genes), limits = NULL)
```


### Get final solution in original space

Simple negativity check
```{r}
solution_scaled <- reverse_solution_projection(dso$st$solution_proj, dso$st$proj)
sum(solution_scaled$W_col < 0) / length(solution_scaled$W_col)
sum(solution_scaled$H_row < 0) / length(solution_scaled$H_row)
plot_negative_proportions_change(dso$st$proj, dso$st$solution_proj)
plot_negative_basis_change(dso$st$proj, dso$st$solution_proj)
plot_matrix_hist_with_negative(solution_scaled$H_row, title = "Proportions distribution", bins = 100)
plot_matrix_hist_with_negative(solution_scaled$W_col, title = "Basis distribution", bins = 100)
boxplot(rowSums(solution_scaled$H_row))
boxplot(colSums(solution_scaled$W_col))
```

```{r}
# Fix negative proportions and basis
solution_scaled$H_row[solution_scaled$H_row < 0] <- 0
solution_scaled$H_row <- t(apply(solution_scaled$H_row, 1, function(x) x / sum(x)))
solution_scaled$W_col[solution_scaled$W_col < 0] <- 0
solution_scaled$W_col <- apply(solution_scaled$W_col, 2, function(x) x / sum(x))
plot_matrix_hist_with_negative(solution_scaled$H_row, title = "Proportions distribution", bins = 100)
plot_matrix_hist_with_negative(solution_scaled$W_col, title = "Basis distribution", bins = 100)
boxplot(rowSums(solution_scaled$H_row))
boxplot(colSums(solution_scaled$W_col))
```

```{r}
# res <- reverse_solution_sinkhorn(solution_scaled, dso$st$scaling)
res <- reverse_sinkhorn_c(solution_scaled$H_row,
                          solution_scaled$W_col,
                          dso$st$scaling$D_vs_row,
                          dso$st$scaling$D_vs_col,
                          dso$st$scaling$iterations)

plot_matrix_hist_with_negative(res$H, title = "Proportions distribution", bins = 100)
plot_matrix_hist_with_negative(res$W, title = "Basis distribution", bins = 100)
boxplot(c(res$H))
boxplot(c(res$W))
boxplot(colSums(res$H))

R <- dso$st$proj$meta$R
S <- dso$st$proj$meta$S
V_ss <- dso$st$scaling$V_row

m <- t(S) %*% S %*% V_ss %*% t(R) %*% R
sum(m < 0) / (nrow(m) * ncol(m))

all(is.na(res$W))
```

```{r fig.width = 14, fig.height = 6}
dso$plot_projected("markers", use_dims = NULL, with_legend = T, pt_size = 0.9, with_history = F)
```

```{r}
so <- add_list_markers(so, dso$get_marker_genes())
```

```{r fig.width=20, fig.height=25}
plot_marker_enrichment(so, dso$get_ct_names(), limits = NULL)
```

```{r, fig.width=40, fig.height=20}
plotlist <- list()
for (ct in dso$get_ct_names()) {
  plotlist[[ct]] <- dso$plot_projected(ct, pmin(dso$get_solution()$H[ct, ], 1), with_history = F, with_solution = F, with_legend = F)
}
cowplot::plot_grid(plotlist=plotlist, ncol=4)
```

```{r, fig.width=20, fig.height=20}
plotlist <- list()
for (ct in dso$get_ct_names()) {
  so_flt[[ct]] <- pmin(dso$get_solution()$H[ct, ], 0.5)
  plotlist[[ct]] <- FeaturePlot(so_flt, feature = ct)
}
cowplot::plot_grid(plotlist=plotlist, ncol=4)
```

```{r fig.width=5, fig.height=5}
fn <- function(x) {
  mx <- which.max(x)
  if (x[mx] > 0) {
    return(mx)
  } else {
    return(NA)
  }
}
so_flt$dualsimplex_cluster <- apply(dso$get_solution()$H, 2, fn)[colnames(so_flt)]
DimPlot(so_flt, group.by = "dualsimplex_cluster", label = T) + NoLegend() + ggtitle("") + NoAxes()
```


# Figures
```{r}
dso <- DualSimplexSolver$from_state("../out/single_cell_hnsc_save_3kg_16ct/")
```


```{r, fig.width=7, fig.height=5}
plt <- DimPlot(so_flt, raster = T) +
  Seurat::NoAxes() +
  ggtitle("") +
  theme(text=element_text(family = "Helvetica", size = 12))

ggsave("../out/sc_a_gse103322_umap.svg", plt, width = 7, height = 5, device = svglite::svglite)
plt
```


```{r fig.width=20, fig.height=10}
plotlist <- list()
for (use_dims in list(2:3, 4:5, 6:7, 8:9)) {
  pt_size <- 0.7
  plts <- dso$plot_projected(
    color_genes = "zero_distance",
    color_samples = as.factor(so_flt[, colnames(dso$get_data())]$ct),
    use_dims = use_dims,
    pt_size = pt_size,
    with_legend = T,
    with_solution = F,
    with_history = F,
    wrap = F
  )
  linewidth <- 0.3

  plotlist[[use_dims[[2]] - 1]] <- plts[[2]] + ggtitle("Cells") + theme(
    legend.position = "none",
    axis.line = element_line(color = "black", size = linewidth),
    axis.title = element_text(size = 18),
    axis.text = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(size = 16, face = "bold")
  ) + xlab(paste0("S", use_dims[[1]])) + ylab(paste0("S", use_dims[[2]]))

  plotlist[[use_dims[[1]] - 1]] <- plts[[1]] + ggtitle("Genes") + theme(
    legend.position = "none",
    axis.line = element_line(color = "black", size = linewidth),
    axis.title = element_text(size = 18),
    axis.text = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_text(size = 16, face = "bold")
  ) + xlab(paste0("R", use_dims[[1]])) + ylab(paste0("R", use_dims[[2]]))
}

plt <- cowplot::plot_grid(plotlist = plotlist, ncol = 4)

ggsave("../out/sc_b_first_dims.svg", plt, width = 20, height = 10, device = svglite::svglite)
plt
```

```{r, fig.width=12, fig.height=6}
knns_genes <- FNN::get.knnx(dso$st$proj$X, dso$st$solution_proj$X, k = 40)
corner_genes <- as.list(as.data.frame(
  apply(knns_genes$nn.index, 1, function(x) rownames(dso$get_data())[x])
))
knns_cells <- FNN::get.knnx(dso$st$proj$Omega, dso$st$solution_proj$Omega, k = 70)
corner_cells <- as.list(as.data.frame(
  apply(knns_cells$nn.index, 1, function(x) colnames(dso$get_data())[x])
))
```

```{r fig.width=4, fig.height=8}
plts <- dso$plot_projected(
  color_genes = which_marker(rownames(dso$get_data()), corner_genes),
  color_samples = which_marker(colnames(dso$get_data()), corner_cells),
  use_dims = NULL,
  pt_size = 1,
  with_legend = F,
  with_solution = T,
  with_history = T,
  color_history = F,
  wrap = F
)
linewidth <- 0.3

plts[[2]] <- plts[[2]] + ggtitle("Cells") + theme(
  axis.line = element_line(color = "black", size = linewidth),
  axis.title = element_text(size = 14),
  axis.text = element_blank(),
  panel.grid = element_blank(),
  plot.title = element_text(size = 14, face = "bold", vjust = -5, hjust = 0.02)
) + xlab("UMAP1") + ylab("UMAP2")

plts[[1]] <- plts[[1]] + ggtitle("Genes") + theme(
  axis.line = element_line(color = "black", size = linewidth),
  axis.title = element_text(size = 14),
  axis.text = element_blank(),
  panel.grid = element_blank(),
  plot.title = element_text(size = 14, face = "bold", vjust = -5, hjust = 0.02)
) + xlab("UMAP1") + ylab("UMAP2")


ggsave(
  "../out/sc_c_corners_genes.svg",
  plts[[1]],
  width = 4,
  height = 4,
  device = svglite::svglite
)
ggsave(
  "../out/sc_c_corners_samples.svg",
  plts[[2]],
  width = 4,
  height = 4,
  device = svglite::svglite
)

cowplot::plot_grid(plotlist = plts, ncol = 1)
```

```{r, fig.width=26, fig.height=12}
plotlist <- list()
for (ctn in 1:dso$get_n_cell_types()) {
  ct <- dso$get_ct_names()[[ctn]]
  so_flt[[ct]] <- pmin(dso$get_solution()$H[ct, ], 0.5)
  mar <- 0
  plotlist[[ct]] <- FeaturePlot(so_flt, feature = ct, raster = T) +
    NoLegend() +
    NoAxes() +
    ggtitle(ctn) +
    theme(
      plot.title = element_text(size = 24, face = "bold", vjust = -7, hjust = 0.05),
      plot.margin = margin(t = mar, r = mar, b = mar, l = mar)
    )
}
plt <- cowplot::plot_grid(plotlist = plotlist, ncol = 6, scale = 1.05)
ggsave("../out/sc_d_proportions.svg", plt, width = 26, height = 12, device = svglite::svglite)
plt
```


```{r, fig.width=12, fig.height=6}
to_plot <- reshape2::melt(t(dso$get_solution()$H))
to_plot$Var2 <- as.character(to_plot$Var2)
to_plot$Var2 <- substr(to_plot$Var2, 11, nchar(to_plot$Var2))
to_plot$Var2 <- factor(to_plot$Var2, levels = as.character(1:dso$get_n_cell_types()))
to_plot <- to_plot[to_plot$value > 0.001, ]
plt <- ggplot(to_plot, aes(x = value, fill = Var2)) +
  geom_histogram(bins = 50) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 0, vjust = 0.8, hjust=0.5, size = 10),
    # axis.title.x = element_blank(),
    axis.title.y = element_text(size = 16),
    axis.title.x = element_text(size = 16),
    legend.position= "none",
    text = element_text(family = "Helvetica", size = 12),
    panel.spacing.x = unit(2, "lines"),
    panel.spacing.y = unit(1, "lines"),
    #strip.text = elem(),
    strip.background = element_blank()
  ) +
  scale_x_continuous(breaks = c(0, 1)) +
  xlab("Cell Type Proportion") +
  ylab("Number of cells") +
  # ylim(c(0, 1000)) +
  facet_wrap(facets = vars(Var2), nrow = 4, scales = "free_y")

ggsave("../out/sc_d_proportions_histograms.svg", plt, width = 12, height = 4, device = svglite::svglite)

plt
```

```{r fig.width=5, fig.height=5}
fn <- function(x) {
  mx <- which.max(x)
  if (x[mx] > 0) {
    return(mx)
  } else {
    return(NA)
  }
}
so_flt$dualsimplex_cluster <- apply(dso$get_solution()$H, 2, fn)[colnames(so_flt)]
plt <- (DimPlot(so_flt, group.by = "dualsimplex_cluster", label = F, raster = T) +
  NoLegend() +
  NoAxes() +
  ggtitle("")) %>% LabelClusters(id = "dualsimplex_cluster", fontface = "bold", color = "black", repel = 0.1, size = 3, box = T)

ggsave("../out/sc_e_clustering.svg", plt, width = 5, height = 5, device = svglite::svglite)
plt
```

```{r fig.width=17, fig.height=4}
basis <- dso$get_solution()$W

# Min-max scaling for display, like in phantasus
basis <- as.data.frame(t(apply(basis, 1, function(x) (x - min(x)) / (max(x) - min(x)))))

ct_order <- c(
  1, 10, 13, 16,  # Fibroblasts
  11, 2, 12, 5, 8,  # Cancer and near epithelium
  6, 9, 7, 14, 15, 3,  # Immune
  4  # Endothelial
)
n_markers <- 5
gaps_after <- c(4, 9, 15)
gaps_after <- rep(gaps_after, each = 3)
col_gaps <- gaps_after * n_markers
col_gaps_small <- cumsum(rep(n_markers, dso$get_n_cell_types()))
col_gaps_small <- col_gaps_small[!col_gaps_small %in% col_gaps]
col_gaps <- c(col_gaps_small, col_gaps)
sele <- unlist(get_signature_markers(dso$get_solution()$W, n_markers)[ct_order])
colnames(basis) <- seq(1, ncol(basis))
plt <- pheatmap::pheatmap(
  t(basis[sele, ct_order]),
  cluster_rows = F,
  cluster_cols = F,
  color = colorRampPalette(c("blue", "white", "red"))(100),
  legend = F,
  gaps_col = col_gaps,
  gaps_row = gaps_after,
  angle_col = 315,
  fontsize_col = 10
)
ggsave("../out/sc_f_marker_genes.svg", plt, width = 15, height = 4, device = svglite::svglite)
```


