---
title: "Figures 6D and 6E: Deconvolution of TCGA-HNSC"
output:
  html_document:
    df_print: paged
    self_contained: yes
---

```{r}
source("../R/figure_utils.R")
source("../R/setup.R")
```

```{r}
save_dir <- "../out/linseed2_save_tcga_hnscc_4kg_9ct_no_hk_neighbours/"
options(`linseed-rasterize` = TRUE)
```

```{r}
lo2 <- Linseed2Solver$from_state(save_dir, save_there = T)
```

```{r fig.width = 14, fig.height = 6}
lo2$plot_projected(use_dims = NULL)
```

```{r}
all_dims <- list(NULL, 2:3, 4:5, 6:7, 8:9)
lo2$set_display_dims(all_dims)
```


## Initialize solution
```{r fig.width = 14, fig.height = 6}
set.seed(13)
lo2$init_solution("select_x")
lo2$plot_projected(use_dims = NULL, with_legend = T)
```

Set convenient order for cell types
```{r fig.width = 14, fig.height = 6}
reorder <- c(5, 4, 2, 9, 3, 7, 8, 1, 6)
lo2$st$solution_proj$D_h <- lo2$st$solution_proj$D_h[reorder, , drop = F]
lo2$st$solution_proj$D_w <- lo2$st$solution_proj$D_w[reorder, , drop = F]
lo2$st$solution_proj$X <- lo2$st$solution_proj$X[reorder, ]
lo2$st$solution_proj$Omega <- lo2$st$solution_proj$Omega[reorder, ]
lo2$plot_projected(use_dims = NULL, with_legend = T)
```


## Optimize solution
```{r fig.width = 14, fig.height = 6}
# For select_x to correct Omega
lo2$optim_solution(650, optim_config(coef_hinge_H = 1, coef_hinge_W = 1, coef_der_X = 0.001, coef_der_Omega = 0.1))
lo2$plot_projected(use_dims = NULL, with_legend = T, from_iter = 1, to_iter = 650)
```


Run this cell several times until convergence.
Choosing coef_hinge parameters is the trickiest part.
```{r}
lr <- 0.001
lo2$optim_solution(1000, optim_config(coef_hinge_H = .01, coef_hinge_W = .01, coef_der_X = lr, coef_der_Omega = lr))
lo2$plot_error_history()
```

```{r fig.width = 11, fig.height = 6}
plt <- lo2$plot_projected(use_dims = NULL, with_legend = F, with_history = T)
ggsave("../out/6d_trajectory.svg", width = 11, height = 6, plot = plt, device = svg)
plt
```


### Get final solution in original space

Simple negativity check
```{r}
solution_scaled <- reverse_solution_projection(lo2$st$solution_proj, lo2$st$proj)
sum(solution_scaled$W_col < 0) / length(solution_scaled$W_col)
sum(solution_scaled$H_row < 0) / length(solution_scaled$H_row)
snc <- reverse_solution_sinkhorn(solution_scaled, lo2$st$scaling)
res <- reverse_sinkhorn_c(solution_scaled$H_row,
                          solution_scaled$W_col,
                          lo2$st$scaling$D_vs_row,
                          lo2$st$scaling$D_vs_col,
                          lo2$st$scaling$iterations)

plot_negative_proportions_change(lo2)
plot_negative_basis_change(lo2)
plot_matrix_hist_with_negative(solution_scaled$H_row, title = "Proportions distribution", bins = 100)
plot_matrix_hist_with_negative(solution_scaled$W_col, title = "Basis distribution", bins = 100)

R <- lo2$st$proj$meta$R
S <- lo2$st$proj$meta$S
V_ss <- lo2$st$scaling$V_row

m <- t(S) %*% S %*% V_ss %*% t(R) %*% R
sum(m < 0) / (nrow(m) * ncol(m))

plot_matrix_hist_with_negative(m, bins = 100)

all(is.na(res$W))
```

```{r}
solution <- lo2$finalize_solution()
```

```{r fig.width = 14, fig.height = 6}
plt <- lo2$plot_projected("markers", use_dims = NULL, with_legend = T, pt_size = 0.9, with_history = F)
ggsave("../out/6e.svg", width = 14, height = 6, plot = plt, device = svg)
plt
```


```{r, fig.width=9, fig.height=5}
plt <- ggplot(reshape2::melt(pmin(t(lo2$get_solution()$H), 1)), aes(x = Var2, y = value, fill = Var2)) +
  geom_boxplot() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.8, hjust=0.5), axis.title.x = element_blank())
ggsave("../out/6d_proportions.svg", plt, width = 9, height = 5, device = svg)
plt
```

```{r}
lo2$save_state()
```



# To move
```{r}
# Write solution data for phantasus
# da <- rbind(lo2$get_solution()$H, exprs(lo2$get_data()))
# dia <- diag(rep(1, ncol(lo2$get_solution()$W)))
# rownames(dia) <- colnames(lo2$get_solution()$W)
# colnames(dia) <- rownames(dia)
# da <- cbind(rbind(dia, lo2$get_solution()$W), da)
# write.table(da, "hnsc_6ct_data.tsv", sep = "\t", quote = F, row.names = T, col.names = T)
# lo2$generate_summary(seurat_obj = seurat_obj, with_animated_optim = FALSE)
```

```{r}
plot_negative_proportions_change <- function(lo_object) {
  N <- lo2$st$proj$meta$N
  M <- lo2$st$proj$meta$M
  K <- lo2$st$proj$meta$K
  errors_statistics <-  lo2$st$solution_proj$optim_history$errors_statistics
  total_H <- N * K
  toPlot <- as.data.frame(errors_statistics[,"neg_props_count", drop=F])
  last_prop_count <- round(toPlot[nrow(toPlot),"neg_props_count"] / total_H,6) * 100
  toPlot$iteration <- 0:(nrow(toPlot) - 1)
  plt <- ggplot(toPlot,aes(y=neg_props_count,x=iteration)) + geom_line() + theme_minimal() +
      xlab("Iteration") + ylab("Negative proportions")+
    annotate("text",  x=Inf, y = Inf, label = paste0(last_prop_count,"%"), vjust=1, hjust=1) +
    ggtitle("Number of negative proportions")
  return(plt)
}


plot_negative_basis_change <- function(lo_object) {
  N <- lo2$st$proj$meta$N
  M <- lo2$st$proj$meta$M
  K <- lo2$st$proj$meta$K
  errors_statistics <-  lo2$st$solution_proj$optim_history$errors_statistics
  total_W <- M * K
  toPlot <- as.data.frame(errors_statistics[,"neg_basis_count",drop=F])
  last_basis_count <- round(toPlot[nrow(toPlot),"neg_basis_count"] / total_W,6) * 100
  toPlot$iteration <- 0:(nrow(toPlot) - 1)
  plt <- ggplot(toPlot,aes(y=neg_basis_count,x=iteration)) + geom_line() + theme_minimal() +
      xlab("Iteration") + ylab("Negative basis")+
      annotate("text",  x=Inf, y = Inf, label = paste0(last_basis_count,"%"), vjust=1, hjust=1) +
    ggtitle("Number of negative basis elements")
  return(plt)
}

plot_matrix_hist_with_negative <- function(data_, title="Distribution of values", ...) {
  toPlot <- as.data.frame(c(data_))
  colnames(toPlot) <- "value"
  toPlot$negative <- (toPlot$value < 0)
  plt <- ggplot(toPlot) + geom_histogram(aes(x=value, fill=negative), stat = "bin", ...) + theme_minimal() + ggtitle(title)
  return(plt)
}
```

